---
title: "Project 1"
author: "Anith Muthalaly"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes some helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# You will need to install it (once) from GitHub.
# library(devtools)
# devtools::install_github("physicsland/ezids")
# Then load the package in your R session.
library(ezids)
```


```{r setup, include=FALSE}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(results="markup", warning = F, message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```

```{r}
```

**Kaggle Link: https://www.kaggle.com/datasets/divyansh22/online-gaming-anxiety-data/data**

# 1: Import File and Data Frame Stuff.

```{r}
# 1 - Read the csv file to create the data frame.
gaming = read.csv("G:/My Drive/Flash Drive Contents/E/Graduate School/The George Washington Univeristy/Data Science/DATS 6101_12 (Morris)/Project 1/GamingStudy_data.csv", header=T)
head(gaming, 5)

# 2 - Display the data frame's structure.
str(gaming)

# 3 - Change certain DSM questions to factor variables.
gaming$GADE <- as.factor(gaming$GADE)
str(gaming$GADE)
gaming$Platform <- as.factor(gaming$Platform)
str(gaming$Platform)
head(gaming, 5)
```

# 2: GADE

```{r}
# 4 - Make a vertical bar chart of GADE results (mean)
library(ggplot2)
ggplot(gaming, aes(x = GADE)) +
  geom_bar(fill = "blue", color = "black", alpha = 0.9) +
  ggtitle("Bar Plot of GADE") +
  xlab("GADE") +
  ylab("Frequency") +
  theme_minimal()
```

# 3: Total GAD Score

```{r}
# 5 - Check if the 'TotalGAD' column exists and is numeric
str(gaming$GAD_T)  # Ensure that GAD_T is a numeric variable

# 6 - Plot a histogram of GAD_T
library(ggplot2)
ggplot(gaming, aes(x = GAD_T)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.9) +
  ggtitle("Histogram of Total GAD Score") +
  xlab("Total GAD Score") +
  ylab("Frequency") +
  theme_minimal()
```


